// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOy1ipTu1gsDcw0BgNOL_b9U_rigCnJeU',
    appId: '1:663828726292:web:82cf345006e496711e1d01',
    messagingSenderId: '663828726292',
    projectId: 'tasknest-1b0f5',
    authDomain: 'tasknest-1b0f5.firebaseapp.com',
    storageBucket: 'tasknest-1b0f5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmq1UWBrD-6-sa1tjw13jOrrQU6--ipaU',
    appId: '1:663828726292:android:50c33ff35128c5001e1d01',
    messagingSenderId: '663828726292',
    projectId: 'tasknest-1b0f5',
    storageBucket: 'tasknest-1b0f5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDusAOI7ZxEeh6KWhkwmj1kEvo9Q_MVeM4',
    appId: '1:663828726292:ios:fdb2c9e14d18c4f01e1d01',
    messagingSenderId: '663828726292',
    projectId: 'tasknest-1b0f5',
    storageBucket: 'tasknest-1b0f5.firebasestorage.app',
    iosClientId: '663828726292-ccg3kk1kmspbumavavp276lh22h5tf2a.apps.googleusercontent.com',
    iosBundleId: 'com.example.tasknest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDusAOI7ZxEeh6KWhkwmj1kEvo9Q_MVeM4',
    appId: '1:663828726292:ios:fdb2c9e14d18c4f01e1d01',
    messagingSenderId: '663828726292',
    projectId: 'tasknest-1b0f5',
    storageBucket: 'tasknest-1b0f5.firebasestorage.app',
    iosClientId: '663828726292-ccg3kk1kmspbumavavp276lh22h5tf2a.apps.googleusercontent.com',
    iosBundleId: 'com.example.tasknest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOy1ipTu1gsDcw0BgNOL_b9U_rigCnJeU',
    appId: '1:663828726292:web:d2a52681b8c8ee2a1e1d01',
    messagingSenderId: '663828726292',
    projectId: 'tasknest-1b0f5',
    authDomain: 'tasknest-1b0f5.firebaseapp.com',
    storageBucket: 'tasknest-1b0f5.firebasestorage.app',
  );

}